name: Stripe Payments CI/CD Pipeline

on:
  push:
    branches:
      - main # Set a branch to watch for changes
    paths:
      - "backend/**"
      - "frontend/**"
      - ".github/workflows/main.yml"
  pull_request:
    branches:
      - main # Set a branch to watch for changes

jobs:
  frontend-CI:
    runs-on: ubuntu-latest
    steps:
      ## Load the source code ##
      - name: Checkout the code
        uses: actions/checkout@v4

      ## Setup Node.js ##
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      ## Install dependencies ##
      - name: Install dependencies
        run: |
          npm install -g yarn
          cd frontend
          yarn install

      ## Run tests ##
      - name: Run tests
        run: |
          cd frontend
          yarn test

      ## Code Quality ##
      - name: Code Quality
        run: |
          cd frontend
          yarn lint
