name: Stripe Payments CI/CD Pipeline

on:
  push:
    branches:
      - main # Set a branch to watch for changes
    paths:
      - "backend/**"
      - "frontend/**"
      - ".github/workflows/main.yml"
  pull_request:
    branches:
      - main # Set a branch to watch for changes

jobs:
  frontend-CI:
    runs-on: ubuntu-latest
    steps:
      ## Load the source code ##
      - name: Checkout the code
        uses: actions/checkout@v4

      ## Setup Node.js ##
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      ## Install dependencies ##
      - name: Install dependencies
        run: |
          npm install -g yarn
          cd frontend
          yarn install

      ## Run tests ##
      - name: Run tests
        run: |
          cd frontend
          yarn test

      ## Code Quality ##
      - name: Code Quality
        run: |
          cd frontend
          yarn lint

      ## Build frontend Artifact ##
      - name: Build frontend
        run: |
          cd frontend
          yarn build

  ## DEPLOY FRONTEND ##
  Deploy-Frontend:
    runs-on: ubuntu-latest
    needs: frontend-CI
    steps:
      ## Load the source code ##
      - name: Checkout the code
        uses: actions/checkout@v4

      ## Deploy to S3 ##
      - name: Deploy to s3
        uses: aws-actions/s3-sync-action@v1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_S3_BUCKET: ${{ secrets.S3_BUCKET }}

      - name: AWS CLI Setup
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-1"

        ## Deploy to S3 ##
      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-west-1"
          SOURCE_DIR: "public"
